//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSTestContrib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSTestContrib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test results are inconclusive because it is not fully implemented:\r\n\r\n{0}.
        /// </summary>
        internal static string AssertMessageTestResultsInconclusive {
            get {
                return ResourceManager.GetString("AssertMessageTestResultsInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test method &apos;{0}&apos; on class &apos;{1}&apos; is an invalid scenario because it is missing a ScenarioDescriptionAttribute..
        /// </summary>
        internal static string ExceptionMessageMessingScenarioDescriptionAttribute {
            get {
                return ResourceManager.GetString("ExceptionMessageMessingScenarioDescriptionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &apos;{0}&apos; is an invalid specification because it is missing a SpecificationDescriptionAttribute..
        /// </summary>
        internal static string ExceptionMessageMissingSpecificationDescriptionAttribute {
            get {
                return ResourceManager.GetString("ExceptionMessageMissingSpecificationDescriptionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state property &apos;{0}&apos; could not be assigned because it has already been assigned with a type that cannot be assigned to. You are trying to assign a value to a property that has previously been declared as a &apos;{1}&apos; instance..
        /// </summary>
        internal static string ExceptionMessageStatePropertyNotAssignable {
            get {
                return ResourceManager.GetString("ExceptionMessageStatePropertyNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the post conditions failed for this specification:\r\n\r\n{0}.
        /// </summary>
        internal static string FailMessageGrammersNotPassed {
            get {
                return ResourceManager.GetString("FailMessageGrammersNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occured whilst processing the specification:\r\n\r\n{0}.
        /// </summary>
        internal static string FailMessageUnhandledWhilstProcessingGrammars {
            get {
                return ResourceManager.GetString("FailMessageUnhandledWhilstProcessingGrammars", resourceCulture);
            }
        }
    }
}
